###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

###############################################################################
# Requirements:
#     - IBM z/OS core collection 1.2.0 or later
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    userid: "{{ userid_survey }}"
    new_owner: "{{ new_owner_survey | default(omit) }}"
    omvs_home_directory: "{{ omvs_home_directory_survey | default('/u/' + (userid | lower)) }}"
    omvs_zfs_data_set_name: "{{ omvs_zfs_data_set_name_survey | default(\"OMVS.USER.\" + (userid | upper) + \".ZFS\") }}"
    bpxprm_data_set: "{{ bpxprm_data_set_survey | default('SYS1.PARMLIB') }}"
    bpxprm_member: "{{ bpxprm_member_survey | default(omit) }}"
    delete_user_data_sets: "{{ delete_user_data_sets_survey | default('true') }}"
    target_charset: "{{ target_charset_survey | default('IBM-1047') }}"

  tasks:
    - name: Print variables, for debugging purposes.
      debug:
        var: "{{ item }}"
      loop:
          - userid
          - new_owner
          - omvs_home_directory
          - omvs_zfs_data_set_name
          - bpxprm_data_set
          - bpxprm_member
          - delete_user_data_sets
          - target_charset

    - name: Remove user from z/OS system
      include_role:
        name: remove-zos-user
