---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    ds_name: "{{ ds_name | default('IBMUSER.FETCH.DATASET') }}"
    src_file: "{{ src_file | default('HELLO.jcl')}}"
    dest_path: "{{ dest_path | default('/tmp/data_set') }}"
  tasks:
    
    - name: Create a sequential data set for demonstration purposes.
      zos_data_set:
        name: "{{ ds_name }}"
        type: seq
        state: present
        replace: true
        format: fb
        record_length: 100
        size: 5M
      register: result

    - name: Remove old /tmp/ds_temp if it exists already, for idempotency.
      file:
        path: "/tmp/ds_temp"
        state: absent
      register: result

    - name: Copy {{ playbook_dir }}/files/{{ src_file }} from project to USS file.
      zos_copy:
        src: "{{ playbook_dir }}/files/{{ src_file }}"
        dest: "/tmp/ds_temp"
      register: result

    - name: Copy the USS file to the sequential data set.
      zos_copy:
        src: "/tmp/ds_temp"
        dest: "{{ ds_name }}"
        remote_src: true
      register: result

    - name: Fetch the created sequential data set and store in {{ dest_path }}.
      zos_fetch:
        src: "{{ ds_name }}"
        dest: "{{ dest_path }}"
        flat: true

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Get copied data set.
      shell: "cat {{ dest_path }}"
      register: ds_contents
      changed_when: False

    - name: Print copied data set's contents from Linux's side.
      debug:
        msg: "{{ ds_contents.stdout_lines }}"